apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "alumet-relay-client.fullname" . }}

  
spec:
  selector:
    matchLabels:
      name: alumet-relay-client
  template:
    metadata:
      labels:
        name: alumet-relay-client
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      #- key: kubernetes.io/hostname
      # operator: Equal
      # value: "edge-master.seed"
      # effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: master
        operator: Exists
        effect: NoSchedule

      serviceAccountName: {{ .Release.Name }}-alumet-reader
      automountServiceAccountToken: true

      containers:
      - name: alumet-relay-client
        image: {{ .Values.global.image.registry }}/alumet-client:0.7.0-alpha
        command: ["./alumet-relay-client", "--config", "alumet-agent.toml"]
#        command: ["sleep", "infinity"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "{{ .Values.resources.memory }}"
            cpu: "{{ .Values.resources.cpu }}"
        volumeMounts:
          - name: sysfs
            mountPath: /sys
          - name: config
            mountPath: /alumet-agent.toml
            subPath: config

        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: RUST_LOG
            value: "{{ .Values.env.RUST_LOG }}"
#        args: [ "{{ .Values.cmd.Arg1 }}" ]


        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SYS_NICE"]

      volumes:
        - name: sysfs
          hostPath:
            path: /sys
            type: "Directory"
        
        - name: config
          configMap:
            name: {{ template "alumet-relay-client.fullname" . }}-config
      
      imagePullSecrets:
        - name: {{ .Values.global.secret }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alumet-relay-client.fullname" . }}-config
data:
  config: |
    max_update_interval = "500ms"

    [plugins.rapl]
    enable = {{ .Values.pluginsRapl.enable }}
    poll_interval = "1s"
    flush_interval = "5s"
    no_perf_events = false
    
    [plugins.perf]
    enable = false
    poll_interval = "1s"
    flush_interval = "5s"
    hardware_events = ["REF_CPU_CYCLES", "CACHE_MISSES", "BRANCH_MISSES"]
    software_events = []
    cache_events = ["LL_READ_MISS"]

    [plugins.k8s]
    enable = {{ .Values.pluginsK8s.enable }}
    path = "/sys/fs/cgroup/kubepods.slice/"
    poll_interval = "1s"
    kubernetes_api_url = "https://kubernetes.default.svc:443"
    hostname = "$NODE_NAME"
    token_retrieval = "file"

    [plugins.socket-control]
    socket_path = "alumet-control.sock"

    [plugins.procfs]
    enable = false

    [plugins.relay-client]
    client_name = "edge-master.seed"
    collector_uri = "{{ .Values.global.plugin.relay.collector_uri }}:{{  .Values.global.service.port }}"
    buffer_size = 200
    buffer_timeout = "30s"
    
    [plugins.EnergyEstimationTdpPlugin]
    poll_interval = "1s"
    tdp = 100.0
    nb_vcpu = 1.0
    nb_cpu = 1.0

    [plugins.energy-attribution]
    enable = {{ .Values.pluginsEnergyAttribution.enable }}