apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "alumet-relay-server.fullname" . }}
#  name: alumet-relay-server

spec:
  strategy:
    rollingUpdate:
  selector:
    matchLabels:
      app: alumet-relay-server
  template:
    metadata:
      labels:
        app: alumet-relay-server
    spec:
    {{- if .Values.plugins.influxdb.enable }}
      # activate init containers only when influxdb plugin is activated
      initContainers:
        - name: wait-for-influxdb
          image: docker.io/busybox:latest
          command: [
            'sh',
            '-c',
            'until nc -vz {{ .Release.Name }}-influxdb2 80; do echo "Waiting for influxdb service to be running"; sleep 2; done;'
          ]
    {{- end }}
      containers:
        - name: alumet-relay-server
          image: {{ .Values.global.image.registry }}/alumet-agent:0.8.0-1_debian_12
          args: ["--config", "/alumet-agent.toml"]
          imagePullPolicy: Always
          resources:
            limits:
              memory: "{{ .Values.resources.memory }}"
              cpu: "{{ .Values.resources.cpu }}"
          volumeMounts:
            - name: config
              mountPath: /alumet-agent.toml
              subPath: config
          env:
            - name: RUST_LOG
              value: "{{ .Values.env.RUST_LOG }}"
            - name: RUST_BACKTRACE
              value: "{{ .Values.env.RUST_BACKTRACE }}"
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.plugins.influxdb.existingSecret }}
                  name: {{ .Values.plugins.influxdb.existingSecret }}
                  {{- else }}
                  # use the default secret created by influxdb
                  name: {{ .Release.Name }}-influxdb2-auth
                  {{- end }}
                  key: admin-token
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            capabilities:
              add: [{{ .Values.securityContext.capabilities }}]
      volumes:
        - name: config
          configMap:
          {{- if .Values.configMap.name }}
            # a config map is created before deployment
            name: {{ .Values.configMap.name }}
          {{- else }}
            name: {{ template "alumet-relay-server.fullname" . }}-config            
          {{- end }}            
      imagePullSecrets:
        - name: {{ .Values.global.secret }}
      tolerations:
        - key: "master"
          operator: "Exists"
          effect: "NoSchedule"
      {{- if .Values.nodeSelector.nodeLabelValue }} 
      nodeSelector:
        {{ .Values.nodeSelector.nodeLabelName }}: {{ .Values.nodeSelector.nodeLabelValue }}
      {{- end }}