apiVersion: v1
kind: Service
metadata:
  name: {{ template "alumet-relay-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: alumet-relay-server
  ports:
    - port: {{ .Values.service.port }}
      name: "relay"
    {{- if .Values.plugins.prometheusExporter.enable }}
    - port: {{ .Values.plugins.prometheusExporter.port }}
      name: "exporter"
    {{ end }}