alumet-relay-server:
  enabled: true
  plugins:
    influxdb:
      enable: false
    csv:
      enable: true

alumet-relay-client:
  enabled: true
  plugins:
    procfs:
      enable: true
    k8s:
      enable: true
      poll_interval: 5s
    energyAttribution:
      enable: true
    EnergyEstimationTdp:
      enable: true
      tdp: 100
      nb_vcpu: 1
      nb_cpu: 1

influxdb2:
  enabled: false

global:
  image:
    registry: ghcr.io/alumet-dev
